INSERT INTO bookings (
    id,
    user_id,
    kost_id,
    tanggal_masuk,
    tipe_sewa,
    durasi,
    durasi_bulan,
    payment_method,
    payment_status,
    payment_proof_data,
    payment_proof_mime_type,
    status,
    created_at
  )
VALUES (
    'id:bigint',
    'user_id:bigint',
    'kost_id:bigint',
    'tanggal_masuk:date',
    'tipe_sewa:enum',
    durasi:int,
    durasi_bulan:int,
    'payment_method:varchar',
    'payment_status:enum',
    'payment_proof_data:longtext',
    'payment_proof_mime_type:varchar',
    'status:enum',
    'created_at:timestamp'
  );